sudo: required
dist: trusty
branches:
  only:
  - master

before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-full
- chmod +x compile.sh

script:
- "./compile.sh"

before_deploy:
- git config --local user.name "Travis CI"
- git config --local user.email "travis@travis-ci.org"
- git tag "$(date +'%Y%m%d%H%M')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure: UbIC7QZa6eeQ17gWUXxRhAVDN22L7LZ8stDsIQtGjfKkCQMD48ZI8uh5fxSlhklef4j9U53xNhGmTtbTsl/l253WGbJHL1YtkneOfcrWYfz1JeGVZ07kQD890TRffqjgF+VkIaGhKSAKtDJzwVAVS+k8H7pUYvFDMHh6M3hMwxydUip+iph2v4OCIi0F5/lyvov4UKt2MVVOP2Uf5/zdZ/cF0FbuLeN6u3YuyRtaEitwD56qntSxEPRNJIYKJxdmtoZekiiONLOJTtWD6Syjlm4beGxoV6ac8QEGO2mwi6X2Wa2/7l3C+WYdnBN+QaidRSsMl1hdpgQItS/fZHJJuNxndSApaIStSVUa5Yy+KKLhJHzTQDqy8hRxnGhLdUsDXRlpox0rKeoVOsneG9C9dnLk3UAAzBr24QJCp9AqlgLjXug78o5r7As7+CwV/lJ6v1MhAYCURJubbHzrM601ntKv273nINrlTYTU/E2bpF1AWAexNksc1/3Mpo/hntF2B12d4wbf7FYrHdrwRDlQBEZrfK8rWcrFlMz04kdGGPqb3vMMOswhJeYekk24leZD/xjV7xuIf/epajLlbcwvXChh5odIyfhwv2Z8yZ1k3TsAlfqHK+jCh2oQkj8LsB0Oa15vvc1L/EVB060WwVA8mnvWQfIRjRiBI3aicf0JVo8=
  file: main.pdf
  on:
    repo: jc0b/Bachelor-Thesis
  skip_cleanup: 'true'

after_success:
- wget http://assets.jacobsburley.com/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget http://assets.jacobsburley.com/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
